version: '3'

services:
  apiacrossmusic:
    build: .
    ports:
      - "8099:8099"
    environment:
      DB_URL: jdbc:mysql://acrossthemusic:3306/across_the_music?createDatabaseIfNotExist=true
      DB_USER_NAME: root
      DB_PASSWORD: Admin
  acrossthemusic:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_PASSWORD: Admin
      MYSQL_DATABASE: across_the_music
      
